version: '3'

services:
  api:
    container_name: question-generator_api
    build:
      context: .
      dockerfile: Dockerfile
    image: question-generator_api
    env_file:
      - .env.docker
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./log:/app/log
      - ./models:/app/models
    ports:
      - "30000:80"
    restart: unless-stopped
    command: gunicorn question_generator.api.main:question_generator_api --bind=0.0.0.0:80 -w 2 -k uvicorn.workers.UvicornWorker
    networks:
      chatbot:
        aliases:
          - question-generator-api

  onmt_server:
    container_name: question-generator_onmt_server
    image: question-generator_api
    env_file:
      - .env.docker
    environment:
      - PYTHONUNBUFFERED=1
      - ONMT_SERVER_HOST=0.0.0.0
    volumes:
        - ./models:/app/models
    command: python run_onmt_server.py
    restart: unless-stopped
    networks:
      chatbot:
        aliases:
          - question-generator-api

networks:
  chatbot:
    external: True
